# **Data Professional Survey cleaning using Pandas**

## **Project overview:**

This is part of a project using the dataset 'Data Professiona Survey' that will be used to create visualizations using Power BI, the data was collected by Alex Freberg from different sources, in this part I will use Pandas to clean it up before importing it into Power BI to create a Dashboard.

In [1]:
import pandas as pd

df = pd.read_csv('Power BI - Final Project.csv')
df

<ipython-input-1-7b2cc7c85210>:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

,Unique ID,Email,Date Taken (America/New_York),Time Taken (America/New_York),Browser,OS,City,Country,Referrer,Time Spent,...,Q6 - How Happy are you in your Current Position with the following? (Management),Q6 - How Happy are you in your Current Position with the following? (Upward Mobility),Q6 - How Happy are you in your Current Position with the following? (Learning New Things),Q7 - How difficult was it for you to break into Data?,"Q8 - If you were to look for a new job today, what would be the most important thing to you?",Q9 - Male/Female?,Q10 - Current Age,Q11 - Which Country do you live in?,Q12 - Highest Level of Education,Q13 - Ethnicity
0,62a33b3db4da29969c62df3d,anonymous,6/10/2022,8:38,NaN,NaN,NaN,NaN,NaN,0:00:44,...,5.0,5.0,7.0,Very Difficult,Remote Work,Male,26,United States,NaN,White or Caucasian
1,62a33ba1bae91e4b8b82e35c,anonymous,6/10/2022,8:40,NaN,NaN,NaN,NaN,NaN,0:01:30,...,2.0,1.0,3.0,Very Difficult,Remote Work,Male,36,Canada,NaN,Asian or Asian American
2,62a33c2cbc6861bf3176bec1,anonymous,6/10/2022,8:42,NaN,NaN,NaN,NaN,NaN,0:02:18,...,5.0,7.0,7.0,Easy,Good Work/Life Balance,Male,23,Other (Please Specify):Nigeria,NaN,Black or African American
3,62a33c8624a26260273822f9,anonymous,6/10/2022,8:43,NaN,NaN,NaN,NaN,NaN,0:02:10,...,10.0,7.0,10.0,Very Easy,Remote Work,Female,35,Canada,NaN,White or Caucasian
4,62a33c91f3072dd892621e03,anonymous,6/10/2022,8:44,NaN,NaN,NaN,NaN,NaN,0:01:51,...,4.0,0.0,1.0,Difficult,Better Salary,Male,44,United States,NaN,Black or African American
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
625,62b525563f28f20328aeee5c,anonymous,6/23/2022,22:45,NaN,NaN,NaN,NaN,NaN,0:00:50,...,6.0,5.0,7.0,Easy,Better Salary,Male,26,United States,Bachelors,White or Caucasian
626,62b5a3e29bc428d5345f6e89,anonymous,6/24/2022,7:45,NaN,NaN,NaN,NaN,NaN,0:03:12,...,7.0,4.0,6.0,Difficult,Better Salary,Male,21,United States,Bachelors,White or Caucasian
627,62b71083f31287f32e189026,anonymous,6/25/2022,9:41,NaN,NaN,NaN,NaN,NaN,0:04:43,...,2.0,1.0,2.0,Difficult,Better Salary,Male,26,Other (Please Specify):Oman,Bachelors,Asian or Asian American
628,62b795033b026e423f287ecd,anonymous,6/25/2022,19:06,NaN,NaN,NaN,NaN,NaN,0:02:17,...,6.0,4.0,3.0,Easy,Other (Please Specify):Career Advancedment,Male,24,Other (Please Specify):Costa Rica,Bachelors,Hispanic or Latino
629,62b89039377223ff07b80fb5,anonymous,6/26/2022,12:58,NaN,NaN,NaN,NaN,NaN,0:01:19,...,7.0,6.0,8.0,Easy,Remote Work,Male,22,United States,Bachelors,Asian or Asian American

### **Remove irrelevant columns:**

We have some empty columns, others that won't necessary for our analysis, so will start with this first, removing any irrelevant columns or empty ones.

In [2]:
#We create a list of the columns we will remove
columns_to_drop = ['Browser', 'OS', 'City', 'Country', 'Referrer', 'Email', 'Time Taken (America/New_York)', 'Time Spent', 'Date Taken (America/New_York)']

df = df.drop(columns=columns_to_drop, axis=1).set_index('Unique ID')
df

,Q1 - Which Title Best Fits your Current Role?,Q2 - Did you switch careers into Data?,Q3 - Current Yearly Salary (in USD),Q4 - What Industry do you work in?,Q5 - Favorite Programming Language,Q6 - How Happy are you in your Current Position with the following? (Salary),Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance),Q6 - How Happy are you in your Current Position with the following? (Coworkers),Q6 - How Happy are you in your Current Position with the following? (Management),Q6 - How Happy are you in your Current Position with the following? (Upward Mobility),Q6 - How Happy are you in your Current Position with the following? (Learning New Things),Q7 - How difficult was it for you to break into Data?,"Q8 - If you were to look for a new job today, what would be the most important thing to you?",Q9 - Male/Female?,Q10 - Current Age,Q11 - Which Country do you live in?,Q12 - Highest Level of Education,Q13 - Ethnicity
Unique ID,,,,,,,,,,,,,,,,,,
62a33b3db4da29969c62df3d,Data Analyst,Yes,106k-125k,Healthcare,Python,9.0,9.0,7.0,5.0,5.0,7.0,Very Difficult,Remote Work,Male,26,United States,NaN,White or Caucasian
62a33ba1bae91e4b8b82e35c,Data Analyst,No,41k-65k,Finance,R,1.0,2.0,5.0,2.0,1.0,3.0,Very Difficult,Remote Work,Male,36,Canada,NaN,Asian or Asian American
62a33c2cbc6861bf3176bec1,Data Engineer,No,0-40k,Other (Please Specify):Clean Energy,Python,0.0,8.0,7.0,5.0,7.0,7.0,Easy,Good Work/Life Balance,Male,23,Other (Please Specify):Nigeria,NaN,Black or African American
62a33c8624a26260273822f9,Other (Please Specify):Analytics Consultant,Yes,150k-225k,Finance,R,10.0,6.0,7.0,10.0,7.0,10.0,Very Easy,Remote Work,Female,35,Canada,NaN,White or Caucasian
62a33c91f3072dd892621e03,Data Analyst,Yes,41k-65k,Healthcare,R,1.0,4.0,4.0,4.0,0.0,1.0,Difficult,Better Salary,Male,44,United States,NaN,Black or African American
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62b525563f28f20328aeee5c,Data Analyst,Yes,125k-150k,Other (Please Specify):Retail,R,8.0,5.0,6.0,6.0,5.0,7.0,Easy,Better Salary,Male,26,United States,Bachelors,White or Caucasian
62b5a3e29bc428d5345f6e89,Other (Please Specify):Data Scientist Intern,No,0-40k,Other (Please Specify):Manufacturing,R,4.0,6.0,7.0,7.0,4.0,6.0,Difficult,Better Salary,Male,21,United States,Bachelors,White or Caucasian
62b71083f31287f32e189026,Student/Looking/None,Yes,0-40k,Tech,Python,1.0,2.0,1.0,2.0,1.0,2.0,Difficult,Better Salary,Male,26,Other (Please Specify):Oman,Bachelors,Asian or Asian American
62b795033b026e423f287ecd,Data Engineer,No,0-40k,Tech,Python,6.0,6.0,6.0,6.0,4.0,3.0,Easy,Other (Please Specify):Career Advancedment,Male,24,Other (Please Specify):Costa Rica,Bachelors,Hispanic or Latino
62b89039377223ff07b80fb5,Data Analyst,No,41k-65k,Other (Please Specify):Automotive,Python,8.0,7.0,6.0,7.0,6.0,8.0,Easy,Remote Work,Male,22,United States,Bachelors,Asian or Asian American

### **Standarize the Data:**

Now let's look at the columns to see what we can do to clean them and deal with any inconsistencies.

One thing I would like to do is to shorten the names of the columns while preserving their meaning for better readability, I will do that depending on the column's names and how convenient it will be.

In [3]:
df = df.rename(columns= {'Q1 - Which Title Best Fits your Current Role?': 'Q1-Current Job Title'})
df

,Q1-Current Job Title,Q2 - Did you switch careers into Data?,Q3 - Current Yearly Salary (in USD),Q4 - What Industry do you work in?,Q5 - Favorite Programming Language,Q6 - How Happy are you in your Current Position with the following? (Salary),Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance),Q6 - How Happy are you in your Current Position with the following? (Coworkers),Q6 - How Happy are you in your Current Position with the following? (Management),Q6 - How Happy are you in your Current Position with the following? (Upward Mobility),Q6 - How Happy are you in your Current Position with the following? (Learning New Things),Q7 - How difficult was it for you to break into Data?,"Q8 - If you were to look for a new job today, what would be the most important thing to you?",Q9 - Male/Female?,Q10 - Current Age,Q11 - Which Country do you live in?,Q12 - Highest Level of Education,Q13 - Ethnicity
Unique ID,,,,,,,,,,,,,,,,,,
62a33b3db4da29969c62df3d,Data Analyst,Yes,106k-125k,Healthcare,Python,9.0,9.0,7.0,5.0,5.0,7.0,Very Difficult,Remote Work,Male,26,United States,NaN,White or Caucasian
62a33ba1bae91e4b8b82e35c,Data Analyst,No,41k-65k,Finance,R,1.0,2.0,5.0,2.0,1.0,3.0,Very Difficult,Remote Work,Male,36,Canada,NaN,Asian or Asian American
62a33c2cbc6861bf3176bec1,Data Engineer,No,0-40k,Other (Please Specify):Clean Energy,Python,0.0,8.0,7.0,5.0,7.0,7.0,Easy,Good Work/Life Balance,Male,23,Other (Please Specify):Nigeria,NaN,Black or African American
62a33c8624a26260273822f9,Other (Please Specify):Analytics Consultant,Yes,150k-225k,Finance,R,10.0,6.0,7.0,10.0,7.0,10.0,Very Easy,Remote Work,Female,35,Canada,NaN,White or Caucasian
62a33c91f3072dd892621e03,Data Analyst,Yes,41k-65k,Healthcare,R,1.0,4.0,4.0,4.0,0.0,1.0,Difficult,Better Salary,Male,44,United States,NaN,Black or African American
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62b525563f28f20328aeee5c,Data Analyst,Yes,125k-150k,Other (Please Specify):Retail,R,8.0,5.0,6.0,6.0,5.0,7.0,Easy,Better Salary,Male,26,United States,Bachelors,White or Caucasian
62b5a3e29bc428d5345f6e89,Other (Please Specify):Data Scientist Intern,No,0-40k,Other (Please Specify):Manufacturing,R,4.0,6.0,7.0,7.0,4.0,6.0,Difficult,Better Salary,Male,21,United States,Bachelors,White or Caucasian
62b71083f31287f32e189026,Student/Looking/None,Yes,0-40k,Tech,Python,1.0,2.0,1.0,2.0,1.0,2.0,Difficult,Better Salary,Male,26,Other (Please Specify):Oman,Bachelors,Asian or Asian American
62b795033b026e423f287ecd,Data Engineer,No,0-40k,Tech,Python,6.0,6.0,6.0,6.0,4.0,3.0,Easy,Other (Please Specify):Career Advancedment,Male,24,Other (Please Specify):Costa Rica,Bachelors,Hispanic or Latino
62b89039377223ff07b80fb5,Data Analyst,No,41k-65k,Other (Please Specify):Automotive,Python,8.0,7.0,6.0,7.0,6.0,8.0,Easy,Remote Work,Male,22,United States,Bachelors,Asian or Asian American

#### **Job Title Standardization:**

In [4]:
df['Q1-Current Job Title'].unique()

array(['Data Analyst', 'Data Engineer',
       'Other (Please Specify):Analytics Consultant ', 'Data Scientist',
       'Student/Looking/None', 'Other (Please Specify):FP&A Analyst',
       'Other (Please Specify):BI Developer ',
       'Other (Please Specify):Manager, Business Intelligence Develop',
       'Other (Please Specify):Business Analyst ',
       'Other (Please Specify):Business Analyst',
       'Other (Please Specify):Business Intelligence Consultant',
       'Other (Please Specify):Sr. Supply Chain Analyst ',
       'Other (Please Specify):Business analyst ',
       'Other (Please Specify):Director of Data Analytics',
       'Other (Please Specify):Learning Management Specialist',
       'Other (Please Specify):Research Analyst',
       'Other (Please Specify):Insights analyst',
       'Other (Please Specify):Does a social media analyst count?',
       'Other (Please Specify):Educator',
       'Other (Please Specify):Business Intelligence Engineer',
       'Other (Please Specify):Research Associate ',
       'Other (Please Specify):Analytics Manager',
       'Other (Please Specify):Manager of a team of Data Analysts',
       'Other (Please Specify):Analyst',
       'Other (Please Specify):Analytics Engineer',
       'Other (Please Specify):Analyst Primary Market Intelligence',
       'Other (Please Specify):software engineer', 'Data Architect',
       'Other (Please Specify):Data Integrity', 'Database Developer',
       'Other (Please Specify):Financial Analyst',
       'Other (Please Specify):Database Manager',
       'Other (Please Specify):Software Developer ',
       'Other (Please Specify):Tableau admin', 'Other (Please Specify)',
       'Other (Please Specify):Reporting Adm',
       'Other (Please Specify):Billing analyst',
       'Other (Please Specify):I work with data tools and can create simple dashboards but I am not a data scientist',
       'Other (Please Specify):Marketing Data Specialist',
       'Other (Please Specify):Jr. Data Scientist',
       'Other (Please Specify):Continuous Quality Improvement Specialist',
       'Other (Please Specify):PMO',
       'Other (Please Specify):System Administrator',
       'Other (Please Specify):Teacher',
       'Other (Please Specify):Consultant',
       'Other (Please Specify):Business Intelligence Developer',
       'Other (Please Specify):Informatics Specialist',
       'Other (Please Specify):Business Analys',
       'Other (Please Specify):Finance Analyst ',
       'Other (Please Specify):Web Developer',
       'Other (Please Specify):Manager ',
       'Other (Please Specify):Junior Software Engineer',
       'Other (Please Specify):Researchers ',
       'Other (Please Specify):Senior Business Analyst',
       'Other (Please Specify):Data Coordinator',
       'Other (Please Specify):Student working as a data analyst intern ',
       'Other (Please Specify):Driver',
       'Other (Please Specify):Data manager',
       'Other (Please Specify):GIS Analyst ',
       'Other (Please Specify):Business Intelligence Analyst',
       'Other (Please Specify):BI consultant ',
       'Other (Please Specify):DBA',
       'Other (Please Specify):Data Steward',
       'Other (Please Specify):Technical consulta',
       'Other (Please Specify):Software Engineer, AI ',
       'Other (Please Specify):Systems configuration ',
       'Other (Please Specify):Sales & marketing',
       'Other (Please Specify):RF Engineer',
       'Other (Please Specify):Support Engineer',
       'Other (Please Specify):Account manager',
       'Other (Please Specify):Incident Manager',
       'Other (Please Specify):Product owner',
       'Other (Please Specify):Presales Engineer ',
       'Other (Please Specify):Predictive Analyst',
       'Other (Please Specify):Ads operations',
       'Other (Please Specify):Power Bi Developer',
       'Other (Please Specify):Software support',
       'Other (Please Specify):Investigation specialist',
       'Other (Please Specify):Director',
       'Other (Please Specify):Data Manager',
       'Other (Please Specify):SAP Security Analyst',
       'Other (Please Specify):BI Manager',
       'Other (Please Specify):Data Scientist Intern'], dtype=object)

As you can see, we have numerous job titles, many of which were entered differently but essentially represent the same roles. To simplify and standardize the dataset, I’ve grouped these job titles based on their similarities, so that they fall under broader, standardized categories. This approach helps in reducing redundancy and ensures consistency when analysing the Data.

In [5]:
# Remove the 'Other (Please Specify):' and only keep what's after the colon
df['Q1-Current Job Title'] = df['Q1-Current Job Title'].str.replace('Other (Please Specify):', '', regex=False)

# Strip leading/trailing spaces and convert to lowercase
df['Q1-Current Job Title'] = df['Q1-Current Job Title'].str.strip().str.lower()

Next I will seperate the jobs into 8 total categories:

- **Data-Related Roles** – for positions related to data science, engineering, and management.
- **Business Intelligence & Analytics** – covering roles involved in business reporting, analytics, and data-driven decision-making.
- **Software Development & IT** – for software engineers, developers, and IT specialists.
- **Finance & Accounting** – focusing on financial and accounting functions.
- **Management & Leadership** – grouping roles that emphasize leadership and team management.
- **Education & Research** – for research-focused and educational roles.
- **Sales & Marketing** – encompassing roles tied to marketing, sales, and customer management.
- **Miscellaneous** – for roles that don’t fit neatly into the other categories.

This grouping allows for a more structured analysis of job roles, making it easier to draw insights and compare similar positions across industries.

In [6]:
# Group 1: Data-Related Roles
data_related_jobs = [
    'data scientist intern', 'jr. data scientist', 'data scientist', 'predictive analyst',
    'data analyst', 'data engineer', 'data coordinator', 'data manager', 
    'data steward', 'data architect', 'data integrity', 'database developer', 
    'database manager', 'dba', 'student working as a data analyst intern'
]

replace_data_related = {job: 'data-related roles' for job in data_related_jobs}
df['Q1-Current Job Title'] = df['Q1-Current Job Title'].replace(replace_data_related)

# Group 2: Business Intelligence & Analytics Jobs
business_intelligence_jobs = [
    'bi developer', 'business intelligence consultant', 'business intelligence engineer', 
    'business intelligence analyst', 'bi consultant', 'analytics consultant', 
    'analytics engineer', 'analytics manager', 'insights analyst', 'marketing data specialist',
    'business analyst', 'business analys', 'senior business analyst', 'analyst', 
    'analyst primary market intelligence', 'business intelligence developer', 
    'does a social media analyst count?'
]

replace_bi_analytics = {job: 'business intelligence & analytics' for job in business_intelligence_jobs}
df['Q1-Current Job Title'] = df['Q1-Current Job Title'].replace(replace_bi_analytics)

# Group 3: Software Development & IT Jobs
software_development_jobs = [
    'software engineer', 'software developer', 'web developer', 'junior software engineer', 
    'system administrator', 'support engineer', 'software support', 'technical consulta', 
    'software engineer, ai', 'systems configuration', 'sap security analyst'
]

replace_software_dev_it = {job: 'software development & it' for job in software_development_jobs}
df['Q1-Current Job Title'] = df['Q1-Current Job Title'].replace(replace_software_dev_it)

# Group 4: Finance & Accounting Jobs
finance_jobs = [
    'fp&a analyst', 'financial analyst', 'finance analyst', 'billing analyst'
]

replace_finance = {job: 'finance & accounting' for job in finance_jobs}
df['Q1-Current Job Title'] = df['Q1-Current Job Title'].replace(replace_finance)

# Group 5: Management & Leadership Jobs
management_jobs = [
    'manager, business intelligence develop', 'director of data analytics', 'analytics manager', 
    'manager of a team of data analysts', 'manager', 'director', 'bi manager', 
    'continuous quality improvement specialist', 'pmo'
]

replace_management = {job: 'management & leadership' for job in management_jobs}
df['Q1-Current Job Title'] = df['Q1-Current Job Title'].replace(replace_management)

# Group 6: Education & Research Jobs
education_research_jobs = [
    'learning management specialist', 'research analyst', 'research associate', 'researchers', 
    'educator', 'teacher'
]

replace_education_research = {job: 'education & research' for job in education_research_jobs}
df['Q1-Current Job Title'] = df['Q1-Current Job Title'].replace(replace_education_research)

# Group 7: Sales & Marketing Jobs
sales_marketing_jobs = [
    'sales & marketing', 'account manager', 'incident manager', 'product owner', 'presales engineer', 'ads operations'
]

replace_sales_marketing = {job: 'sales & marketing' for job in sales_marketing_jobs}
df['Q1-Current Job Title'] = df['Q1-Current Job Title'].replace(replace_sales_marketing)

# Group 8: Miscellaneous Jobs
miscellaneous_jobs = [
    'student/looking/none', 'i work with data tools and can create simple dashboards but i am not a data scientist', 
    'driver', 'gis analyst', 'informatics specialist', 'consultant', 'investigation specialist', 'power bi developer',
    'tableau admin', 'reporting adm', 'rf engineer', 'other (please specify)'
]

replace_miscellaneous = {job: 'miscellaneous' for job in miscellaneous_jobs}
df['Q1-Current Job Title'] = df['Q1-Current Job Title'].replace(replace_miscellaneous)

In [7]:
df['Q1-Current Job Title'].unique()

array(['data-related roles', 'business intelligence & analytics',
       'miscellaneous', 'finance & accounting', 'management & leadership',
       'sr. supply chain analyst', 'education & research',
       'software development & it', 'sales & marketing'], dtype=object)

#### **Use Mean Values For Q3:**

In [8]:
df['Q3 - Current Yearly Salary (in USD)'].unique()

array(['106k-125k', '41k-65k', '0-40k', '150k-225k', '125k-150k',
       '86k-105k', '66k-85k', '225k+'], dtype=object)

Now in the Q3 column we have a range of salaries, we will replace these values with their mean value.

In [9]:
def salary_range_mean(x):
    x = x.replace('k', '000').replace('+', '').split('-')
    if len(x) == 1:
        return int(x[0])
    elif len(x) == 2:
        min_salary = int(x[0])
        max_salary = int(x[1])
        return (min_salary + max_salary)/2

# Apply the function to the 'q3' column
df['Q3 - Current Yearly Salary (in USD)'] = df['Q3 - Current Yearly Salary (in USD)'].apply(salary_range_mean)

#### **Industry Standarization:**

In [10]:
df['Q4 - What Industry do you work in?'].unique()

array(['Healthcare', 'Finance', 'Other (Please Specify):Clean Energy',
       'Other (Please Specify):Coworking space ',
       'Other (Please Specify):Retail', 'Telecommunication',
       'Other (Please Specify):Logistics',
       'Other (Please Specify):Igaming', 'Tech', 'Education',
       'Construction', 'Other (Please Specify):Aviation',
       'Other (Please Specify):Insurance',
       'Other (Please Specify):Energy',
       'Other (Please Specify):Oil and gas', 'Other (Please Specify)',
       'Other (Please Specify):Automotive',
       'Other (Please Specify):Automotive ',
       'Other (Please Specify):Utili',
       'Other (Please Specify):Not working yet',
       'Other (Please Specify):Manufa',
       'Other (Please Specify):Manufacturing (Chemicals)',
       'Other (Please Specify):Currently studying . Previously worked in Power Generation',
       'Other (Please Specify):Not working at the moment, but previously I have been into Education industry',
       'Other (Please Specify):Third Party Logistics ',
       'Other (Please Specify):Food & Beverage ',
       'Other (Please Specify):Marketing',
       'Other (Please Specify):Advertising',
       'Other (Please Specify):Staffing and Recruting ',
       'Other (Please Specify):Biotech',
       'Other (Please Specify):Consulting',
       'Other (Please Specify):Consumer Elec',
       'Other (Please Specify):Semiconductor manufacturing',
       'Other (Please Specify):Supply Chain - warehousing, transpiration and ',
       'Other (Please Specify):Distribution',
       'Other (Please Specify):Customer Service',
       'Other (Please Specify):Ecom', 'Other (Please Specify):Consulti',
       'Other (Please Specify):State Government',
       'Other (Please Specify):Culture',
       'Other (Please Specify):Government',
       'Other (Please Specify):Manufacturing',
       'Other (Please Specify):Cons', 'Other (Please Specify):Wholesale',
       'Other (Please Specify):Energy ',
       'Other (Please Specify):Government programs',
       'Other (Please Specify):Supply Chain',
       'Other (Please Specify):Entertainment',
       'Other (Please Specify):Aerospace',
       'Other (Please Specify):Foodservice Franchising',
       'Other (Please Specify):Government ',
       'Other (Please Specify):Entertainment ',
       'Other (Please Specify):Energy (oil and gas)',
       'Other (Please Specify):Market research',
       'Other (Please Specify):hospitality', 'Real Estate',
       'Other (Please Specify):Chemical Manufacturing',
       'Other (Please Specify):Poultry',
       'Other (Please Specify):Renewable Resources',
       'Other (Please Specify):Customer service ',
       'Other (Please Specify): Manufacturering ',
       'Other (Please Specify):sports',
       'Other (Please Specify):fashion/online store',
       'Other (Please Specify):I am a student',
       'Other (Please Specify):Marketing ',
       'Other (Please Specify):Hospitality ', 'Agriculture',
       'Other (Please Specify):Medical industry ',
       'Other (Please Specify):Management',
       'Other (Please Specify):Warehouse',
       'Other (Please Specify):Non profit Animal Welfare',
       'Other (Please Specify):Insurance ', 'Other (Please Specify):none',
       'Other (Please Specify):Social work ',
       'Other (Please Specify):E-commerce', 'Other (Please Specify):IT',
       'Other (Please Specify):Legal',
       'Other (Please Specify):Media & advertising ',
       'Other (Please Specify):Utilities',
       'Other (Please Specify):Audit Firm',
       'Other (Please Specify):Sports',
       'Other (Please Specify):Sports/Marketing',
       'Other (Please Specify):Nonprofit',
       'Other (Please Specify):Law Enforcement',
       'Other (Please Specify):last mile delivery logistics',
       'Other (Please Specify):Arrosp',
       'Other (Please Specify):Demography and Social Statistics ',
       'Other (Please Specify):i`m currently student',
       'Other (Please Specify):None', 'Other (Please Specify):Manuf',
       'Other (Please Specify):Student',
       'Other (Please Specify):Automobile Industry',
       'Other (Please Specify):Fmcg',
       'Other (Please Specify):NGO - Legislation ',
       'Other (Please Specify):Culinary',
       'Other (Please Specify):Customer support ',
       'Other (Please Specify):Cosmetics ',
       'Other (Please Specify):Digital Mar',
       'Other (Please Specify):Home maker ',
       'Other (Please Specify):I am student. ',
       'Other (Please Specify):Unemployed, trying to switch career',
       'Other (Please Specify):Utilities ',
       'Other (Please Specify):Maritime',
       'Other (Please Specify):Ecommerce',
       'Other (Please Specify):Electronics',
       'Other (Please Specify):Logistics and warehousing',
       'Other (Please Specify):Public transport',
       'Other (Please Specify):Urbanism', 'Other (Please Specify):Reta',
       'Other (Please Specify):Avia', 'Other (Please Specify):State',
       'Other (Please Specify):Looking for job',
       'Other (Please Specify):Sensors',
       'Other (Please Specify):Professional Services',
       'Other (Please Specify):Food and bece',
       'Other (Please Specify):Research (non-clincial)',
       'Other (Please Specify):Gover', 'Other (Please Specify):Defense',
       'Other (Please Specify):Foodservice',
       'Other (Please Specify):Data insights company',
       'Other (Please Specify):Not currently working',
       'Other (Please Specify):Food and Beverages',
       'Other (Please Specify):Government Administration',
       'Other (Please Specify):Outsourcing ',
       'Other (Please Specify):Cobsukting',
       'Other (Please Specify):Workforce ',
       'Other (Please Specify):General contractor',
       'Other (Please Specify):Police / Emergency Services',
       'Other (Please Specify):Consumer retail',
       'Other (Please Specify):Home and living',
       'Other (Please Specify):Non Profit Organization',
       'Other (Please Specify):Air transpo',
       'Other (Please Specify):Distribution ',
       'Other (Please Specify):None for now',
       'Other (Please Specify):Retails',
       'Other (Please Specify):Digital Marketing ',
       'Other (Please Specify):Homelessness',
       'Other (Please Specify):Retail ',
       'Other (Please Specify):Direct Marketing',
       'Other (Please Specify):FMCG',
       'Other (Please Specify):Taking bootcamp',
       'Other (Please Specify):Space & Defense',
       'Other (Please Specify):Automobile (cars)',
       'Other (Please Specify):Interning in Sciences, Weather and Meteorological data',
       'Other (Please Specify):Beverage and foods',
       'Other (Please Specify):Transportation'], dtype=object)

It's almost similar to what we had in the first column, so we will proceed with a similar process.

In [11]:
# Remove the 'Other (Please Specify):' and only keep what's after the colon
df['Q4 - What Industry do you work in?'] = df['Q4 - What Industry do you work in?'].str.replace('Other (Please Specify):', '', regex=False)

# Strip leading/trailing spaces and convert to lowercase
df['Q4 - What Industry do you work in?'] = df['Q4 - What Industry do you work in?'].str.strip().str.lower()

The industries were grouped into broader categories to allow for better analysis and easier comparison across different sectors. Below is a brief description of each category:

1. **Technology & IT**: 
   This category includes industries focused on technology development, software, IT services, telecommunications, and e-commerce.

2. **Healthcare & Medical**: 
   This category covers industries related to health services, biotechnology, pharmaceutical companies, and medical research.

3. **Finance & Insurance**: 
   Includes industries involved in banking, insurance, auditing, and other financial services.

4. **Manufacturing & Engineering**: 
   This category encompasses industries related to manufacturing of goods, engineering, and related fields like construction, electronics, and defense.

5. **Retail & Consumer Goods**: 
   Includes industries dealing with consumer goods, retail, and fast-moving consumer goods (FMCG), as well as consumer electronics.

6. **Energy & Utilities**: 
   This category covers industries involved in energy production, oil and gas, renewable resources, and utilities.

7. **Transportation & Logistics**: 
   Includes industries focusing on the transportation of goods, logistics services, warehousing, maritime, and public transport.

8. **Government & Public Sector**: 
   This category is for government-related industries, including public services, law enforcement, and government programs.

9. **Education & Nonprofit**: 
   Covers industries related to education, nonprofit organizations, and social work.

10. **Food & Beverage**: 
    Industries involved in food production, beverage services, franchising, and related sectors are included in this category.

11. **Consulting & Professional Services**: 
    This category includes industries involved in consulting services, staffing, and other professional services.

12. **Entertainment & Media**: 
    Includes industries related to media, entertainment, marketing, sports, and gaming.

13. **Real Estate & Construction**: 
    This category covers real estate, construction, and home services industries.

14. **Other/Miscellaneous**: 
    Includes industries that don’t fit into the other categories, including individuals currently unemployed or studying, customer support, legal, and other unspecified fields.

This categorization provides a structured way to analyze the industries and make meaningful comparisons across different sectors.

In [12]:
# Group 1: Technology & IT
tech_it_jobs = [
    'tech', 'it', 'e-commerce', 'ecommerce', 'digital marketing', 'digital mar', 'sensors', 
    'ecom', 'data insights company', 'telecommunication'
]

replace_tech_it = {job: 'technology & it' for job in tech_it_jobs}
df['Q4 - What Industry do you work in?'] = df['Q4 - What Industry do you work in?'].replace(replace_tech_it)

# Group 2: Healthcare & Medical
healthcare_medical_jobs = [
    'healthcare', 'medical industry', 'biotech', 'research (non-clincial)', 
    'pharmaceutical', 'cosmetics'
]

replace_healthcare_medical = {job: 'healthcare & medical' for job in healthcare_medical_jobs}
df['Q4 - What Industry do you work in?'] = df['Q4 - What Industry do you work in?'].replace(replace_healthcare_medical)

# Group 3: Finance & Insurance
finance_insurance_jobs = [
    'finance', 'insurance', 'audit firm', 'banking', 'consumer finance'
]

replace_finance_insurance = {job: 'finance & insurance' for job in finance_insurance_jobs}
df['Q4 - What Industry do you work in?'] = df['Q4 - What Industry do you work in?'].replace(replace_finance_insurance)

# Group 4: Manufacturing & Engineering
manufacturing_engineering_jobs = [
    'clean energy', 'oil and gas', 'chemical manufacturing', 'semiconductor manufacturing', 
    'manufacturing (chemicals)', 'manufacturering', 'manufa', 'manufacturing', 
    'automobile industry', 'automotive', 'aerospace', 'arrosp', 'defense', 
    'space & defense', 'automobile (cars)', 'manuf'
]

replace_manufacturing_engineering = {job: 'manufacturing & engineering' for job in manufacturing_engineering_jobs}
df['Q4 - What Industry do you work in?'] = df['Q4 - What Industry do you work in?'].replace(replace_manufacturing_engineering)

# Group 5: Retail & Consumer Goods
retail_consumer_goods_jobs = [
    'retail', 'retails', 'consumer retail', 'home and living', 'fashion/online store', 
    'home maker', 'consumer elec', 'fmcg', 'wholesale', 'reta', 'electronics'
]

replace_retail_consumer_goods = {job: 'retail & consumer goods' for job in retail_consumer_goods_jobs}
df['Q4 - What Industry do you work in?'] = df['Q4 - What Industry do you work in?'].replace(replace_retail_consumer_goods)

# Group 6: Energy & Utilities
energy_utilities_jobs = [
    'energy', 'energy (oil and gas)', 'renewable resources', 'utilities', 'utili', 
    'currently studying . previously worked in power generation'
]

replace_energy_utilities = {job: 'energy & utilities' for job in energy_utilities_jobs}
df['Q4 - What Industry do you work in?'] = df['Q4 - What Industry do you work in?'].replace(replace_energy_utilities)

# Group 7: Transportation & Logistics
transportation_logistics_jobs = [
    'transportation', 'logistics', 'logistics and warehousing', 'last mile delivery logistics', 
    'warehousing', 'air transpo', 'aviation', 'public transport', 'urbanism', 
    'maritime', 'third party logistics', 'supply chain - warehousing, transpiration and', 
    'distribution', 'warehouse', 'supply chain', 'avia'
]

replace_transportation_logistics = {job: 'transportation & logistics' for job in transportation_logistics_jobs}
df['Q4 - What Industry do you work in?'] = df['Q4 - What Industry do you work in?'].replace(replace_transportation_logistics)

# Group 8: Government & Public Sector
government_public_sector_jobs = [
    'government', 'state government', 'government programs', 'government administration', 
    'state', 'police / emergency services', 'law enforcement', 'gover'
]

replace_government_public_sector = {job: 'government & public sector' for job in government_public_sector_jobs}
df['Q4 - What Industry do you work in?'] = df['Q4 - What Industry do you work in?'].replace(replace_government_public_sector)

# Group 9: Education & Nonprofit
education_nonprofit_jobs = [
    'education', 'nonprofit', 'non profit organization', 'ngo - legislation', 
    'demography and social statistics', 'non profit animal welfare', 'social work', 
    'homelessness', 'taking bootcamp', 'interning in sciences, weather and meteorological data', 
    'not working at the moment, but previously i have been into education industry', 
    'i am a student', 'i`m currently student', 'i am student.', 'student'
]

replace_education_nonprofit = {job: 'education & nonprofit' for job in education_nonprofit_jobs}
df['Q4 - What Industry do you work in?'] = df['Q4 - What Industry do you work in?'].replace(replace_education_nonprofit)

# Group 10: Food & Beverage
food_beverage_jobs = [
    'food & beverage', 'beverage and foods', 'foodservice franchising', 'foodservice', 
    'food and bece', 'food and beverages', 'poultry', 'culinary', 'agriculture'
]

replace_food_beverage = {job: 'food & beverage' for job in food_beverage_jobs}
df['Q4 - What Industry do you work in?'] = df['Q4 - What Industry do you work in?'].replace(replace_food_beverage)

# Group 11: Consulting & Professional Services
consulting_professional_services_jobs = [
    'consulting', 'consulti', 'consulting services', 'workforce', 'outsourcing', 
    'staffing and recruting', 'market research', 'customer service', 'professional services', 
    'cobsukting', 'cons', 'customer support'
]

replace_consulting_professional_services = {job: 'consulting & professional services' for job in consulting_professional_services_jobs}
df['Q4 - What Industry do you work in?'] = df['Q4 - What Industry do you work in?'].replace(replace_consulting_professional_services)

# Group 12: Entertainment & Media
entertainment_media_jobs = [
    'entertainment', 'media & advertising', 'marketing', 'sports/marketing', 
    'sports', 'culture', 'igaming', 'direct marketing', 'hospitality', 'advertising'
]

replace_entertainment_media = {job: 'entertainment & media' for job in entertainment_media_jobs}
df['Q4 - What Industry do you work in?'] = df['Q4 - What Industry do you work in?'].replace(replace_entertainment_media)

# Group 13: Real Estate & Construction
real_estate_construction_jobs = [
    'real estate', 'construction', 'general contractor', 'coworking space'
]

replace_real_estate_construction = {job: 'real estate & construction' for job in real_estate_construction_jobs}
df['Q4 - What Industry do you work in?'] = df['Q4 - What Industry do you work in?'].replace(replace_real_estate_construction)

# Group 14: Other/Miscellaneous
miscellaneous_jobs = [
    'other (please specify)', 'none', 'not currently working', 'looking for job', 
    'unemployed, trying to switch career', 'none for now', 'management', 
    'homemaker', 'legal', 'not working yet'
]

replace_miscellaneous = {job: 'miscellaneous' for job in miscellaneous_jobs}
df['Q4 - What Industry do you work in?'] = df['Q4 - What Industry do you work in?'].replace(replace_miscellaneous)

In [13]:
df['Q4 - What Industry do you work in?'].unique()

array(['healthcare & medical', 'finance & insurance',
       'manufacturing & engineering', 'real estate & construction',
       'retail & consumer goods', 'technology & it',
       'transportation & logistics', 'entertainment & media',
       'education & nonprofit', 'energy & utilities', 'miscellaneous',
       'food & beverage', 'consulting & professional services',
       'government & public sector'], dtype=object)

#### **Standarize the Programming Language**

In [14]:
# Remove the 'Other (Please Specify):' and only keep what's after the colon
df['Q5 - Favorite Programming Language'] = df['Q5 - Favorite Programming Language'].str.replace('Other:', '', regex=False)

# Strip leading/trailing spaces and convert to lowercase
df['Q5 - Favorite Programming Language'] = df['Q5 - Favorite Programming Language'].str.strip().str.lower()

We look at the options we have.

In [15]:
df['Q5 - Favorite Programming Language'].unique()

array(['python', 'r', 'sql',
       'mostly use sql but that’s not programming language..',
       'qlik sense script', 'power bi', 'javascript',
       "if sql is categorised as a programming language then i will definitely say sql. since i am still learning, i can't give a definite answer in relation to the abover mentioned but for the sake of choosing i will say r then followed by python",
       'c/c++', 'i don’t know any', 'dont require', 'other',
       'knowledge of excel and sql yet',
       "i don't use programming in my role", 'excel/sql', 'unknown',
       'sql postgres', 'dax', 'vba', 'stata', 'excel',
       'i currently do not work with programming languages yet', 'altery',
       'none', 'c#', 'just started learning',
       'i mean, i mostly work in sql and its variants?', 'java', 'sas',
       'na', 'mainly use excel',
       'sql because that is all i know really well so far.', 'matlab',
       'sql &  plsql', 'php', 'sas sql', 'none at the moment',
       'i do analysis and create presentations based on datasets provided by others'],
      dtype=object)

I will group the languages based on their frequency, if it has a considerable number of occurences it will have it's own category, if not it will be put into one category called **other** where I will group all of them.

In [16]:
df['Q5 - Favorite Programming Language'].value_counts()

Q5 - Favorite Programming Language
python                                                                                                                                                                                                                                             420
r                                                                                                                                                                                                                                                  101
sql                                                                                                                                                                                                                                                 43
other                                                                                                                                                                                                                                                9
c/c++                                                                                                                                                                                                                                                7
javascript                                                                                                                                                                                                                                           6
none                                                                                                                                                                                                                                                 6
dax                                                                                                                                                                                                                                                  5
excel                                                                                                                                                                                                                                                2
vba                                                                                                                                                                                                                                                  2
sas                                                                                                                                                                                                                                                  2
sas sql                                                                                                                                                                                                                                              1
i mean, i mostly work in sql and its variants?                                                                                                                                                                                                       1
just started learning                                                                                                                                                                                                                                1
none at the moment                                                                                                                                                                                                                                   1
na                                                                                                                                                                                                                                                   1
java                                                                                                                                                                                                                                                 1
php                                                                                                                                                                                                                                                  1
mainly use excel                                                                                                                                                                                                                                     1
sql because that is all i know really well so far.                                                                                                                                                                                                   1
matlab                                                                                                                                                                                                                                               1
sql &  plsql                                                                                                                                                                                                                                         1
c#                                                                                                                                                                                                                                                   1
stata                                                                                                                                                                                                                                                1
altery                                                                                                                                                                                                                                               1
i currently do not work with programming languages yet                                                                                                                                                                                               1
sql postgres                                                                                                                                                                                                                                         1
unknown                                                                                                                                                                                                                                              1
excel/sql                                                                                                                                                                                                                                            1
i don't use programming in my role                                                                                                                                                                                                                   1
knowledge of excel and sql yet                                                                                                                                                                                                                       1
dont require                                                                                                                                                                                                                                         1
i don’t know any                                                                                                                                                                                                                                     1
if sql is categorised as a programming language then i will definitely say sql. since i am still learning, i can't give a definite answer in relation to the abover mentioned but for the sake of choosing i will say r then followed by python      1
power bi                                                                                                                                                                                                                                             1
qlik sense script                                                                                                                                                                                                                                    1
mostly use sql but that’s not programming language..                                                                                                                                                                                                 1
i do analysis and create presentations based on datasets provided by others                                                                                                                                                                          1
Name: count, dtype: int64

In [17]:
# Function to clean and consolidate programming language responses
def consolidate_programming_languages(language):
    
    if 'python' in language:
        return 'Python'
    elif language == 'r':
        return 'R'
    elif 'sql' in language and 'dax' not in language:
        return 'SQL'
    elif 'c/c++' in language or 'c++' in language or 'c#' in language:
        return 'C/C++'
    elif 'javascript' in language:
        return 'JavaScript'
    elif 'dax' in language:
        return 'DAX'
    elif 'excel' in language:
        return 'Excel'
    elif any(x in language for x in ["don't", "do not", "none", "na", "unknown", "not use", "not working", "not require"]):
        return 'None' 
    else:
        return 'Other' 
        
# Apply the function to clean the column
df['Q5 - Favorite Programming Language'] = df['Q5 - Favorite Programming Language'].apply(consolidate_programming_languages)

# Display the unique values in the cleaned column
print(df['Q5 - Favorite Programming Language'].value_counts())

Q5 - Favorite Programming Language
Python        421
R             101
SQL            51
Other          23
None           12
C/C++           8
JavaScript      6
DAX             5
Excel           3
Name: count, dtype: int64

#### **Rename the Q6 columns**

For all the Q6 questions I will change the names of the columns without altering the meaning for better readability.

In [18]:
df = df.rename(columns={
    'Q6 - How Happy are you in your Current Position with the following? (Salary)': 'Q6 - How happy are you with salary',
    'Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance)': 'Q6 - How happy are you with work/life balance',
    'Q6 - How Happy are you in your Current Position with the following? (Coworkers)': 'Q6 - How happy are you with coworkers',
    'Q6 - How Happy are you in your Current Position with the following? (Management)': 'Q6 - How happy are you with management',
    'Q6 - How Happy are you in your Current Position with the following? (Upward Mobility)': 'Q6 - How happy are you with upward mobility',
    'Q6 - How Happy are you in your Current Position with the following? (Learning New Things)': 'Q6 - How happy are you with learning new things'
})

#### **Standarize the Country**

In [19]:
df['Q11 - Which Country do you live in?'].unique()

array(['United States', 'Canada', 'Other (Please Specify):Nigeria',
       'Other (Please Specify):Republic democratic of Congo ',
       'Other (Please Specify)', 'Other (Please Specify):Serbia',
       'Other (Please Specify):Argentina', 'United Kingdom',
       'Other (Please Specify):Niger', 'Other (Please Specify):Kenya',
       'Other (Please Specify):Azerbaijan',
       'Other (Please Specify):Sudan', 'India',
       'Other (Please Specify):Japan', 'Other (Please Specify):Greece',
       'Other (Please Specify):Perú ', 'Other (Please Specify):Australia',
       'Other (Please Specify):Spain', 'Other (Please Specify):Kenya ',
       'Other (Please Specify):Barbados',
       'Other (Please Specify):South Africa',
       'Other (Please Specify):Colombia',
       'Other (Please Specify):Germany',
       'Other (Please Specify):Bulgaria', 'Other (Please Specify):Turkey',
       'Other (Please Specify):France', 'Other (Please Specify):Thailand',
       'Other (Please Specify):Netherlands',
       'Other (Please Specify):Denmark', 'Other (Please Specify):Brazil',
       'Other (Please Specify):Mexico', 'Other (Please Specify):Chile',
       'Other (Please Specify):Costa Rica',
       'Other (Please Specify):Vietnam',
       'Other (Please Specify):Nigeria ',
       'Other (Please Specify):Portugal', 'Other (Please Specify):turkey',
       'Other (Please Specify):Egypt', 'Other (Please Specify):Pakistan',
       'Other (Please Specify):Ireland ', 'Other (Please Specify):Poland',
       'Other (Please Specify):Mozambique',
       'Other (Please Specify):Egypt ', 'Other (Please Specify):Israel',
       'Other (Please Specify):Singapore',
       'Other (Please Specify):Belgium', 'Other (Please Specify):UAE',
       'Other (Please Specify): Somalia', 'Other (Please Specify):Kosovo',
       'Other (Please Specify):Iraq', 'Other (Please Specify):Romania',
       'Other (Please Specify):Peru',
       'Other (Please Specify):Philippines',
       'Other (Please Specify):Malaysia',
       'Other (Please Specify):nigeria', 'Other (Please Specify):Ghana',
       'Other (Please Specify):Portugsl',
       'Other (Please Specify):Macedonia', 'Other (Please Specify):Irel',
       'Other (Please Specify):Morocco',
       'Other (Please Specify):Costa Rica ',
       'Other (Please Specify):Iran',
       'Other (Please Specify):South Africa ',
       'Other (Please Specify):Bangladesh ', 'Other (Please Specify):Ire',
       'Other (Please Specify):Antigua ',
       'Other (Please Specify):Venezuela',
       'Other (Please Specify):Brazik',
       'Other (Please Specify):South Korea',
       'Other (Please Specify):Panama',
       'Other (Please Specify):indonesia',
       'Other (Please Specify):Angola',
       'Other (Please Specify):Africa (Nigeria)',
       'Other (Please Specify):Fin', 'Other (Please Specify):Austr',
       'Other (Please Specify):Leba',
       'Other (Please Specify):Saudi Arabia',
       'Other (Please Specify):United Arab Emirates ',
       'Other (Please Specify):Zambia', 'Other (Please Specify):ghana',
       'Other (Please Specify):Uruguay',
       'Other (Please Specify):Indonesia',
       'Other (Please Specify):Hong Kong',
       'Other (Please Specify):TUNISIA',
       'Other (Please Specify):Sri lanka', 'Other (Please Specify):Kenua',
       'Other (Please Specify):Argentina ',
       'Other (Please Specify):Liberia', 'Other (Please Specify):SG',
       'Other (Please Specify):Aisa', 'Other (Please Specify):Argentine',
       'Other (Please Specify):Sweden',
       'Other (Please Specify):Saudi Arabia ',
       'Other (Please Specify):Algeria', 'Other (Please Specify):Ireland',
       'Other (Please Specify):uzb', 'Other (Please Specify):Morocco ',
       'Other (Please Specify):Oman'], dtype=object)

In [20]:
# Remove the 'Other (Please Specify):' and only keep what's after the colon
df['Q11 - Which Country do you live in?'] = df['Q11 - Which Country do you live in?'].str.replace('Other (Please Specify):', '', regex=False)

# Strip leading/trailing spaces and convert to lowercase
df['Q11 - Which Country do you live in?'] = df['Q11 - Which Country do you live in?'].str.strip().str.lower()

In [21]:
df['Q11 - Which Country do you live in?'].unique()

array(['united states', 'canada', 'nigeria',
       'republic democratic of congo', 'other (please specify)', 'serbia',
       'argentina', 'united kingdom', 'niger', 'kenya', 'azerbaijan',
       'sudan', 'india', 'japan', 'greece', 'perú', 'australia', 'spain',
       'barbados', 'south africa', 'colombia', 'germany', 'bulgaria',
       'turkey', 'france', 'thailand', 'netherlands', 'denmark', 'brazil',
       'mexico', 'chile', 'costa rica', 'vietnam', 'portugal', 'egypt',
       'pakistan', 'ireland', 'poland', 'mozambique', 'israel',
       'singapore', 'belgium', 'uae', 'somalia', 'kosovo', 'iraq',
       'romania', 'peru', 'philippines', 'malaysia', 'ghana', 'portugsl',
       'macedonia', 'irel', 'morocco', 'iran', 'bangladesh', 'ire',
       'antigua', 'venezuela', 'brazik', 'south korea', 'panama',
       'indonesia', 'angola', 'africa (nigeria)', 'fin', 'austr', 'leba',
       'saudi arabia', 'united arab emirates', 'zambia', 'uruguay',
       'hong kong', 'tunisia', 'sri lanka', 'kenua', 'liberia', 'sg',
       'aisa', 'argentine', 'sweden', 'algeria', 'uzb', 'oman'],
      dtype=object)

In [22]:
country_mapping = {
    'portugsl': 'portugal',
    'brazik': 'brazil',
    'irel': 'ireland',
    'ire': 'ireland',
    'antigua': 'antigua and barbuda',
    'africa (nigeria)': 'nigeria',
    'fin': 'finland',
    'austr': 'australia',
    'leba': 'lebanon',
    'aisa': 'asia', 
    'kenua': 'kenya',
    'sg': 'singapore',
    'uzb': 'uzbekistan',
    'uae': 'united arab emirates',
    'perú': 'peru',  
    'argentine': 'argentina'
}

# Apply the replacements to the DataFrame
df['Q11 - Which Country do you live in?'] = df['Q11 - Which Country do you live in?'].replace(country_mapping)

In [23]:
df['Q11 - Which Country do you live in?'].unique()

array(['united states', 'canada', 'nigeria',
       'republic democratic of congo', 'other (please specify)', 'serbia',
       'argentina', 'united kingdom', 'niger', 'kenya', 'azerbaijan',
       'sudan', 'india', 'japan', 'greece', 'peru', 'australia', 'spain',
       'barbados', 'south africa', 'colombia', 'germany', 'bulgaria',
       'turkey', 'france', 'thailand', 'netherlands', 'denmark', 'brazil',
       'mexico', 'chile', 'costa rica', 'vietnam', 'portugal', 'egypt',
       'pakistan', 'ireland', 'poland', 'mozambique', 'israel',
       'singapore', 'belgium', 'united arab emirates', 'somalia',
       'kosovo', 'iraq', 'romania', 'philippines', 'malaysia', 'ghana',
       'macedonia', 'morocco', 'iran', 'bangladesh',
       'antigua and barbuda', 'venezuela', 'south korea', 'panama',
       'indonesia', 'angola', 'finland', 'lebanon', 'saudi arabia',
       'zambia', 'uruguay', 'hong kong', 'tunisia', 'sri lanka',
       'liberia', 'asia', 'sweden', 'algeria', 'uzbekistan', 'oman'],
      dtype=object)

#### **Standarize the Ethnicity**

In [24]:
df['Q13 - Ethnicity'].unique()

array(['White or Caucasian', 'Asian or Asian American',
       'Black or African American', 'Hispanic or Latino',
       'Other (Please Specify):Latino with Italian roots',
       'Other (Please Specify):African',
       'Other (Please Specify):South Asian',
       'Other (Please Specify):Indian',
       'Other (Please Specify):Kenyan African ',
       'Other (Please Specify):Black African, Zimbabwean Citizen',
       'Other (Please Specify):Human',
       "Other (Please Specify):Race isn't a thing",
       'Other (Please Specify):Middleeas',
       'Other (Please Specify):Mixed ( Caucasian / African-American )',
       'Other (Please Specify):Half Asian half African ',
       'Other (Please Specify):Brown',
       'Other (Please Specify):Prefer not to ans',
       'Other (Please Specify):N/A', 'Other (Please Specify):African ',
       'Other (Please Specify)', 'Other (Please Specify):Kurdish',
       'Native Hawaiian or other Pacific Islander',
       'Other (Please Specify):Bangladeshi',
       'Other (Please Specify):Pakistani',
       'Other (Please Specify):Russian', 'Other (Please Specify):Egyp',
       'Other (Please Specify):Half black and half white',
       'Other (Please Specify):7', 'Other (Please Specify):Bla',
       'Other (Please Specify):Moroccan',
       'Other (Please Specify):Indian ', 'Other (Please Specify):Arab ',
       'Other (Please Specify):Sudanese African ',
       'American Indian or Alaska Native',
       'Other (Please Specify):Bi-racial people should be able to check 2 options in 2022. ',
       'Other (Please Specify):Melayu',
       'Other (Please Specify):Dravidian', 'Other (Please Specify):arab',
       'Other (Please Specify):Asian',
       'Other (Please Specify):South Indian ',
       'Other (Please Specify):Greek', 'Other (Please Specify):Nigeria',
       'Other (Please Specify):Arab',
       'Other (Please Specify):Arabian (from Maghreb)',
       'Other (Please Specify):Malay'], dtype=object)

In [25]:
# Remove the 'Other (Please Specify):' and only keep what's after the colon
df['Q13 - Ethnicity'] = df['Q13 - Ethnicity'].str.replace('Other (Please Specify):', '', regex=False)

# Strip leading/trailing spaces and convert to lowercase
df['Q13 - Ethnicity'] = df['Q13 - Ethnicity'].str.strip().str.lower()

In [26]:
df['Q13 - Ethnicity'].unique()

array(['white or caucasian', 'asian or asian american',
       'black or african american', 'hispanic or latino',
       'latino with italian roots', 'african', 'south asian', 'indian',
       'kenyan african', 'black african, zimbabwean citizen', 'human',
       "race isn't a thing", 'middleeas',
       'mixed ( caucasian / african-american )',
       'half asian half african', 'brown', 'prefer not to ans', 'n/a',
       'other (please specify)', 'kurdish',
       'native hawaiian or other pacific islander', 'bangladeshi',
       'pakistani', 'russian', 'egyp', 'half black and half white', '7',
       'bla', 'moroccan', 'arab', 'sudanese african',
       'american indian or alaska native',
       'bi-racial people should be able to check 2 options in 2022.',
       'melayu', 'dravidian', 'asian', 'south indian', 'greek', 'nigeria',
       'arabian (from maghreb)', 'malay'], dtype=object)

In [27]:
df['Q13 - Ethnicity'].value_counts()

Q13 - Ethnicity
white or caucasian                                             239
asian or asian american                                        155
black or african american                                      101
hispanic or latino                                              73
indian                                                          15
african                                                          6
american indian or alaska native                                 4
arab                                                             3
native hawaiian or other pacific islander                        2
black african, zimbabwean citizen                                1
human                                                            1
arabian (from maghreb)                                           1
nigeria                                                          1
greek                                                            1
south indian                                                     1
asian                                                            1
dravidian                                                        1
melayu                                                           1
bi-racial people should be able to check 2 options in 2022.      1
latino with italian roots                                        1
sudanese african                                                 1
south asian                                                      1
moroccan                                                         1
bla                                                              1
7                                                                1
half black and half white                                        1
egyp                                                             1
russian                                                          1
pakistani                                                        1
bangladeshi                                                      1
kenyan african                                                   1
kurdish                                                          1
other (please specify)                                           1
n/a                                                              1
prefer not to ans                                                1
brown                                                            1
half asian half african                                          1
mixed ( caucasian / african-american )                           1
middleeas                                                        1
race isn't a thing                                               1
malay                                                            1
Name: count, dtype: int64

I will create groups for each group of ethnicities that fit together and only keep those with a considerable number of occurences, the other ones will be put in the same **other** group.

In [28]:
ethnicity_mapping = {
    # High-frequency categories to retain
    'white or caucasian': 'White/Caucasian',
    'greek': 'White/Caucasian',
    'russian': 'White/Caucasian',

    'asian or asian american': 'Asian/Asian American',
    'asian': 'Asian/Asian American',
    'south asian': 'Asian/Asian American',
    'indian': 'Asian/Asian American',
    'south indian': 'Asian/Asian American',
    'pakistani': 'Asian/Asian American',
    'bangladeshi': 'Asian/Asian American',
    'dravidian': 'Asian/Asian American',
    'melayu': 'Asian/Asian American',
    'malay': 'Asian/Asian American',

    'black or african american': 'Black/African American',
    'african': 'Black/African American',
    'black african, zimbabwean citizen': 'Black/African American',
    'sudanese african': 'Black/African American',
    'kenyan african': 'Black/African American',
    'nigeria': 'Black/African American',  
    'hispanic or latino': 'Hispanic/Latino',
    'latino with italian roots': 'Hispanic/Latino',

    # Middle Eastern/North African category to retain
    'arab': 'Middle Eastern/North African',
    'arabian (from maghreb)': 'Middle Eastern/North African',
    'moroccan': 'Middle Eastern/North African',
    'middleeas': 'Middle Eastern/North African',
    'kurdish': 'Middle Eastern/North African',

    # Consolidate remaining entries into "Other"
    'american indian or alaska native': 'Other',
    'native hawaiian or other pacific islander': 'Other',
    'human': 'Other',
    'bi-racial people should be able to check 2 options in 2022.': 'Other',
    'half asian half african': 'Other',
    '7': 'Other',
    'n/a': 'Other',
    'prefer not to ans': 'Other',
    'brown': 'Other',
    'bla': 'Other',
    'egyp': 'Other',
    'other (please specify)': 'Other',
    'race isn\'t a thing': 'Other',
    'mixed ( caucasian / african-american )': 'Other',
    'half black and half white': 'Other',
    'i don’t know any': 'Other'
}

# Apply the mapping to the ethnicity column
df['Q13 - Ethnicity'] = df['Q13 - Ethnicity'].replace(ethnicity_mapping)

# Display the cleaned unique values
print(df['Q13 - Ethnicity'].value_counts())

Q13 - Ethnicity
White/Caucasian                 241
Asian/Asian American            178
Black/African American          111
Hispanic/Latino                  74
Other                            19
Middle Eastern/North African      7
Name: count, dtype: int64

In [29]:
df

,Q1-Current Job Title,Q2 - Did you switch careers into Data?,Q3 - Current Yearly Salary (in USD),Q4 - What Industry do you work in?,Q5 - Favorite Programming Language,Q6 - How happy are you with salary,Q6 - How happy are you with work/life balance,Q6 - How happy are you with coworkers,Q6 - How happy are you with management,Q6 - How happy are you with upward mobility,Q6 - How happy are you with learning new things,Q7 - How difficult was it for you to break into Data?,"Q8 - If you were to look for a new job today, what would be the most important thing to you?",Q9 - Male/Female?,Q10 - Current Age,Q11 - Which Country do you live in?,Q12 - Highest Level of Education,Q13 - Ethnicity
Unique ID,,,,,,,,,,,,,,,,,,
62a33b3db4da29969c62df3d,data-related roles,Yes,115500.0,healthcare & medical,Python,9.0,9.0,7.0,5.0,5.0,7.0,Very Difficult,Remote Work,Male,26,united states,NaN,White/Caucasian
62a33ba1bae91e4b8b82e35c,data-related roles,No,53000.0,finance & insurance,R,1.0,2.0,5.0,2.0,1.0,3.0,Very Difficult,Remote Work,Male,36,canada,NaN,Asian/Asian American
62a33c2cbc6861bf3176bec1,data-related roles,No,20000.0,manufacturing & engineering,Python,0.0,8.0,7.0,5.0,7.0,7.0,Easy,Good Work/Life Balance,Male,23,nigeria,NaN,Black/African American
62a33c8624a26260273822f9,business intelligence & analytics,Yes,187500.0,finance & insurance,R,10.0,6.0,7.0,10.0,7.0,10.0,Very Easy,Remote Work,Female,35,canada,NaN,White/Caucasian
62a33c91f3072dd892621e03,data-related roles,Yes,53000.0,healthcare & medical,R,1.0,4.0,4.0,4.0,0.0,1.0,Difficult,Better Salary,Male,44,united states,NaN,Black/African American
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62b525563f28f20328aeee5c,data-related roles,Yes,137500.0,retail & consumer goods,R,8.0,5.0,6.0,6.0,5.0,7.0,Easy,Better Salary,Male,26,united states,Bachelors,White/Caucasian
62b5a3e29bc428d5345f6e89,data-related roles,No,20000.0,manufacturing & engineering,R,4.0,6.0,7.0,7.0,4.0,6.0,Difficult,Better Salary,Male,21,united states,Bachelors,White/Caucasian
62b71083f31287f32e189026,miscellaneous,Yes,20000.0,technology & it,Python,1.0,2.0,1.0,2.0,1.0,2.0,Difficult,Better Salary,Male,26,oman,Bachelors,Asian/Asian American
62b795033b026e423f287ecd,data-related roles,No,20000.0,technology & it,Python,6.0,6.0,6.0,6.0,4.0,3.0,Easy,Other (Please Specify):Career Advancedment,Male,24,costa rica,Bachelors,Hispanic/Latino
62b89039377223ff07b80fb5,data-related roles,No,53000.0,manufacturing & engineering,Python,8.0,7.0,6.0,7.0,6.0,8.0,Easy,Remote Work,Male,22,united states,Bachelors,Asian/Asian American

Now the Data is ready, I will convert it to a csv and then import it into Power BI to complete the analysis.

In [30]:
df.to_csv('Data Professional Survey.csv')